name: guidy
description: Smart Guide Stores App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^1.1.0
  image_pickers: ^2.0.0+2
  awesome_dialog: ^3.0.2
  modal_progress_hud_nsn: ^0.4.0
  awesome_snackbar_content: ^0.1.0
  flutter_custom_selector: ^0.0.3
  flutter_multi_select_items: ^0.4.2
  direct_select_flutter: ^1.1.1
  flashy_tab_bar2: ^0.0.5
  floating_frosted_bottom_bar: ^0.0.1
  shared_preferences: ^2.0.15
  path: ^1.8.0
  flutter_local_notifications: ^16.1.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^10.1.0
  geocoding: ^2.0.4
  iconly: ^1.0.1
  bottom_picker: ^2.0.1
  age_calculator: ^1.0.0
  tap_to_expand: ^0.6.1
  image_picker: ^1.0.4
  ntp: ^2.0.0
  dot_navigation_bar:
  rflutter_alert:
  shaky_animated_listview:
  permission_handler: ^10.0.0
  calendar_date_picker2: ^0.5.5
  carousel_slider:
  flutter_screenutil:
  flutter_rating_bar:
  flutter_phoenix: ^1.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  dropdown_button2: ^1.9.2
  restart_app: ^1.1.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf


    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
